// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/umputun/stash/app/store"
)

// AuditStoreMock is a mock implementation of web.AuditStore.
//
//	func TestSomethingThatUsesAuditStore(t *testing.T) {
//
//		// make and configure a mocked web.AuditStore
//		mockedAuditStore := &AuditStoreMock{
//			QueryAuditFunc: func(ctx context.Context, q store.AuditQuery) ([]store.AuditEntry, int, error) {
//				panic("mock out the QueryAudit method")
//			},
//		}
//
//		// use mockedAuditStore in code that requires web.AuditStore
//		// and then make assertions.
//
//	}
type AuditStoreMock struct {
	// QueryAuditFunc mocks the QueryAudit method.
	QueryAuditFunc func(ctx context.Context, q store.AuditQuery) ([]store.AuditEntry, int, error)

	// calls tracks calls to the methods.
	calls struct {
		// QueryAudit holds details about calls to the QueryAudit method.
		QueryAudit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q store.AuditQuery
		}
	}
	lockQueryAudit sync.RWMutex
}

// QueryAudit calls QueryAuditFunc.
func (mock *AuditStoreMock) QueryAudit(ctx context.Context, q store.AuditQuery) ([]store.AuditEntry, int, error) {
	if mock.QueryAuditFunc == nil {
		panic("AuditStoreMock.QueryAuditFunc: method is nil but AuditStore.QueryAudit was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Q   store.AuditQuery
	}{
		Ctx: ctx,
		Q:   q,
	}
	mock.lockQueryAudit.Lock()
	mock.calls.QueryAudit = append(mock.calls.QueryAudit, callInfo)
	mock.lockQueryAudit.Unlock()
	return mock.QueryAuditFunc(ctx, q)
}

// QueryAuditCalls gets all the calls that were made to QueryAudit.
// Check the length with:
//
//	len(mockedAuditStore.QueryAuditCalls())
func (mock *AuditStoreMock) QueryAuditCalls() []struct {
	Ctx context.Context
	Q   store.AuditQuery
} {
	var calls []struct {
		Ctx context.Context
		Q   store.AuditQuery
	}
	mock.lockQueryAudit.RLock()
	calls = mock.calls.QueryAudit
	mock.lockQueryAudit.RUnlock()
	return calls
}
