// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/umputun/stash/app/store"
)

// AuditLoggerMock is a mock implementation of web.AuditLogger.
//
//	func TestSomethingThatUsesAuditLogger(t *testing.T) {
//
//		// make and configure a mocked web.AuditLogger
//		mockedAuditLogger := &AuditLoggerMock{
//			LogAuditFunc: func(ctx context.Context, entry store.AuditEntry) error {
//				panic("mock out the LogAudit method")
//			},
//		}
//
//		// use mockedAuditLogger in code that requires web.AuditLogger
//		// and then make assertions.
//
//	}
type AuditLoggerMock struct {
	// LogAuditFunc mocks the LogAudit method.
	LogAuditFunc func(ctx context.Context, entry store.AuditEntry) error

	// calls tracks calls to the methods.
	calls struct {
		// LogAudit holds details about calls to the LogAudit method.
		LogAudit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entry is the entry argument value.
			Entry store.AuditEntry
		}
	}
	lockLogAudit sync.RWMutex
}

// LogAudit calls LogAuditFunc.
func (mock *AuditLoggerMock) LogAudit(ctx context.Context, entry store.AuditEntry) error {
	if mock.LogAuditFunc == nil {
		panic("AuditLoggerMock.LogAuditFunc: method is nil but AuditLogger.LogAudit was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Entry store.AuditEntry
	}{
		Ctx:   ctx,
		Entry: entry,
	}
	mock.lockLogAudit.Lock()
	mock.calls.LogAudit = append(mock.calls.LogAudit, callInfo)
	mock.lockLogAudit.Unlock()
	return mock.LogAuditFunc(ctx, entry)
}

// LogAuditCalls gets all the calls that were made to LogAudit.
// Check the length with:
//
//	len(mockedAuditLogger.LogAuditCalls())
func (mock *AuditLoggerMock) LogAuditCalls() []struct {
	Ctx   context.Context
	Entry store.AuditEntry
} {
	var calls []struct {
		Ctx   context.Context
		Entry store.AuditEntry
	}
	mock.lockLogAudit.RLock()
	calls = mock.calls.LogAudit
	mock.lockLogAudit.RUnlock()
	return calls
}
